#Requires -Version 7.0

# Tasks list — SCTASK fulfillment work units under a RITM.
# Source: sharepoint-itsm-schema.xlsx, sheet "3. Tasks"
. (Join-Path $PSScriptRoot '_helpers.ps1')

function Provision-TasksList {
    param([string]$ListTitle = 'Tasks')
    Write-Host "`n=== $ListTitle ===" -ForegroundColor Cyan

    Ensure-PnPList -Title $ListTitle `
        -Description 'Catalog Tasks (SCTASK) — fulfillment work units. One or many per Request Item. Generated by the workflow on Request Item approval.' `
        -EnableVersioning $true -MajorVersionLimit 25 | Out-Null

    Ensure-PnPField -ListTitle $ListTitle -Spec @{ InternalName='TaskNumber'; DisplayName='Task Number'; Type='Text'; Required=$true; Indexed=$true; MaxLength=32; Description='Catalog Task unique ID (SCTASK-prefix)' }
    Ensure-PnPField -ListTitle $ListTitle -Spec @{ InternalName='ParentRitm'; DisplayName='Parent Request Item'; Type='Lookup'; LookupList='Request Items'; LookupField='RitmNumber'; Required=$true; Indexed=$true }
    Ensure-PnPField -ListTitle $ListTitle -Spec @{ InternalName='TaskState'; DisplayName='Status'; Type='Choice'; Choices=@('Open','In Progress','On Hold','Closed Complete','Closed Incomplete','Closed Skipped','Cancelled'); Required=$true; Indexed=$true }
    Ensure-PnPField -ListTitle $ListTitle -Spec @{ InternalName='AssignedTo'; DisplayName='Assigned To'; Type='User'; Indexed=$true }
    Ensure-PnPField -ListTitle $ListTitle -Spec @{ InternalName='AssignmentGroup'; DisplayName='Assignment Group'; Type='User' }
    Ensure-PnPField -ListTitle $ListTitle -Spec @{ InternalName='ShortDescription'; DisplayName='Short Description'; Type='Text'; Required=$true; MaxLength=255 }
    Ensure-PnPField -ListTitle $ListTitle -Spec @{ InternalName='Description'; DisplayName='Description'; Type='Note'; RichText=$false }
    Ensure-PnPField -ListTitle $ListTitle -Spec @{ InternalName='WorkNotes'; DisplayName='Work Notes'; Type='Note'; RichText=$false; AppendOnly=$true }
    Ensure-PnPField -ListTitle $ListTitle -Spec @{ InternalName='OpenedDate'; DisplayName='Opened'; Type='DateTime'; Required=$true }
    Ensure-PnPField -ListTitle $ListTitle -Spec @{ InternalName='ClosedDate'; DisplayName='Closed'; Type='DateTime' }
    Ensure-PnPField -ListTitle $ListTitle -Spec @{ InternalName='LinkedJobId'; DisplayName='Linked Job ID'; Type='Text'; MaxLength=64; Description='If automated, the Provisioning Job that handled this task' }
    Ensure-PnPField -ListTitle $ListTitle -Spec @{ InternalName='SortOrder'; DisplayName='Sort Order'; Type='Number'; Description='Defines task execution order within a Request Item' }

    # Phase 3.1 — explicit JobType column so the SCTASK→PJ bridge can route deterministically
    # without parsing the Description free-text field. Empty = human-fulfilled task.
    Ensure-PnPField -ListTitle $ListTitle -Spec @{
        InternalName='JobType'; DisplayName='Job Type'; Type='Text'; MaxLength=64
        Description='From the catalog item TaskTemplates. Drives the Catalog Task → Provisioning Job bridge. Empty = no automation; this task is fulfilled manually by AssignmentGroup.'
    }
}

